### ISSUE TITLE
Crash when running the auto_mapping_ros.launch file

### ISSUE THREAD

**Issue by shortstheory** [YashTrikannad/auto_mapping_ros#2] opened 2020-07-17 15:03 UTC
Hi

I am not able to run the automapper when using the .launch file. I get the below message in ROS:

```
setting /run_id to 5c4670a4-c83e-11ea-a6bd-0242c6d6c736
process[rosout-1]: started with pid [3692]
started core service [/rosout]
process[fmt_star_server-2]: started with pid [3695]
process[auto_mapping_ros_node-3]: started with pid [3696]
[ INFO] [1594998076.166168157]: Global Planner is waiting for action server to start.
fmt_star_server: /usr/include/boost/smart_ptr/shared_ptr.hpp:728: typename boost::detail::sp_dereference<T>::type boost::shared_ptr<T>::operator*() const [with T = const nav_msgs::OccupancyGrid_<std::allocator<void> >; typename boost::detail::sp_dereference<T>::type = const nav_msgs::OccupancyGrid_<std::allocator<void> >&]: Assertion `px != 0' failed.
[fmt_star_server-2] process has died [pid 3695, exit code -6, cmd /home/nic/catkin_ws/devel/lib/fmt_star/fmt_star_server __name:=fmt_star_server __log:=/home/nic/.ros/log/5c4670a4-c83e-11ea-a6bd-0242c6d6c736/fmt_star_server-2.log].
log file: /home/nic/.ros/log/5c4670a4-c83e-11ea-a6bd-0242c6d6c736/fmt_star_server-2*.log
^C[auto_mapping_ros_node-3] killing on exit
^C[auto_mapping_ros_node-3] escalating to SIGTERM
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by YashTrikannad** [comment] 2020-07-19 07:25
Can you give me more information of the context, So I can try and recreate this bug on my system
Is it the first time you are trying to launch?
Are you using the original levine map or is it some other map?

Also, just to narrow down the root cause of this issue and where it is originating from ( `auto_mapping_ros` / `fmt_star_ros`, can you try and run the server and test client in the `fmt_star_ros` library. Previously this error used to originate from the `fmt_star_ros` library when sample points were generated outside the map boundary but that issue was resolved in one of the previous commits. Although this still seems to be an error related to the map @shortstheory

**Comment by YashTrikannad** [comment] 2020-08-01 19:19
Closing the issue as no follow-up.

**Closed as completed by YashTrikannad** 2020-08-01 19:19 UTC
